### ISSUE TITLE
Readme.MD

### ISSUE THREAD

**Issue by injkgz** [temarusanov/logardian#10]
1) Описание основных методов warn, verbose, log, error и т.д. с описанием кейсов, где они должны использоваться
2) Варианты создания лейблов и layer'ов. Как с ними работать, зачем нужно это разделение
3) Если есть всякие нетривиальные проблемы/механизмы поведения, о которых ты знаешь, нужно добавить описание решения проблем с ними => в либе rabbitmq должен быть логгер по сути и так - если его нет, то как туда добавить и как работать с этим логгером в самом проекте
3) Как скрывать трейс в логах?
4) зависимости залочить все, посмотреть текущую сборку в package-lock.json и залочить зависимости под последние рабочие
5) логи совместимы с pm2? как будет происходить разделение на error/debug/log?
6) либа не скомпиленная лежит, при установке её придётся компилить?
7) есть стандарт разделения на layer/labels/level? Именование label'ов?

**Comment by temarusanov** [comment]
@injkgz please transalte issue and change issue title

**Comment by temarusanov** [comment]
Closed for closed team discussion
